# Generated by Django 2.1.15 on 2020-06-12 07:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('community', '0003_article_like_users'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='content',
            field=models.CharField(max_length=150),
        ),
    ]
