# Generated by Django 2.1.15 on 2020-06-11 04:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0001_initial'),
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='exclude_movies',
            field=models.ManyToManyField(blank=True, related_name='exclude_users', to='movies.Movie'),
        ),
        migrations.AddField(
            model_name='user',
            name='later_movies',
            field=models.ManyToManyField(blank=True, related_name='later_users', to='movies.Movie'),
        ),
        migrations.AddField(
            model_name='user',
            name='like_genres',
            field=models.ManyToManyField(blank=True, related_name='genre_like_users', to='movies.Genre'),
        ),
        migrations.AddField(
            model_name='user',
            name='like_movies',
            field=models.ManyToManyField(blank=True, related_name='like_users', to='movies.Movie'),
        ),
        migrations.AddField(
            model_name='user',
            name='nickname',
            field=models.CharField(default='익명', max_length=10),
        ),
        migrations.AddField(
            model_name='user',
            name='profile_image',
            field=models.ImageField(blank=True, upload_to=''),
        ),
    ]
