# Generated by Django 2.1.15 on 2020-06-11 05:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_auto_20200611_1438'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='like_genres',
            field=models.ManyToManyField(blank=True, related_name='genre_like_users', to='movies.Genre'),
        ),
        migrations.AlterField(
            model_name='user',
            name='profile_image',
            field=models.ImageField(default='default.jpg', upload_to='profile'),
        ),
    ]
